"""Starter aptitude question bank.

Each tuple: (category, difficulty 1-3, question text, [A, B, C, D], index of correct option, explanation)
Admins can add more questions from the Admin page.
"""

CATEGORIES = [
    "Quantitative Aptitude",
    "Logical Reasoning",
    "Verbal Ability",
    "Data Interpretation",
]

Q = "Quantitative Aptitude"
L = "Logical Reasoning"
V = "Verbal Ability"
D = "Data Interpretation"

QUESTIONS = [
    # ---- Quantitative Aptitude ----
    (Q, 1, "A train 120 m long crosses a pole in 6 seconds. What is its speed?",
     ["15 m/s", "20 m/s", "24 m/s", "30 m/s"], 1,
     "Speed = distance / time = 120 / 6 = 20 m/s."),
    (Q, 1, "What is 15% of 240?",
     ["30", "32", "36", "40"], 2,
     "0.15 x 240 = 36."),
    (Q, 2, "The ages of two people are in the ratio 3:5 and their sum is 48. What is the older person's age?",
     ["18", "24", "30", "36"], 2,
     "3x + 5x = 48, so x = 6 and the older age is 5 x 6 = 30."),
    (Q, 1, "A shopkeeper buys an item for Rs 500 and sells it at 20% profit. What is the selling price?",
     ["Rs 550", "Rs 580", "Rs 600", "Rs 620"], 2,
     "20% of 500 = 100, so SP = 600."),
    (Q, 1, "If 2^x = 64, what is x?",
     ["4", "5", "6", "8"], 2,
     "64 = 2^6."),
    (Q, 1, "Simple interest on Rs 2000 at 5% per annum for 3 years is?",
     ["200", "300", "350", "400"], 1,
     "SI = P x R x T / 100 = 2000 x 5 x 3 / 100 = 300."),
    (Q, 2, "What is the LCM of 12 and 18?",
     ["6", "12", "36", "72"], 2,
     "12 = 2^2 x 3 and 18 = 2 x 3^2, so LCM = 2^2 x 3^2 = 36."),
    (Q, 2, "A can finish a job in 10 days and B in 15 days. Working together, how many days will they take?",
     ["5", "6", "7", "8"], 1,
     "Combined rate = 1/10 + 1/15 = 1/6, so 6 days."),
    (Q, 2, "Find the next number in the series: 2, 6, 12, 20, 30, ?",
     ["36", "40", "42", "48"], 2,
     "Differences are 4, 6, 8, 10, 12, so the next term is 30 + 12 = 42."),
    (Q, 1, "What is the probability of getting a head in a single toss of a fair coin?",
     ["1/4", "1/3", "1/2", "1"], 2,
     "There are two equally likely outcomes, so the probability is 1/2."),

    # ---- Logical Reasoning ----
    (L, 1, "Find the odd one out: Dog, Cat, Cow, Carrot",
     ["Dog", "Cat", "Cow", "Carrot"], 3,
     "Carrot is a plant. The others are animals."),
    (L, 1, "Find the next number: 1, 4, 9, 16, ?",
     ["20", "24", "25", "36"], 2,
     "These are perfect squares: 5^2 = 25."),
    (L, 1, "A is taller than B. B is taller than C. Who is the shortest?",
     ["A", "B", "C", "Cannot be determined"], 2,
     "A > B > C, so C is the shortest."),
    (L, 2, "What is the angle between the hour and minute hands at 3:00?",
     ["45 degrees", "60 degrees", "90 degrees", "120 degrees"], 2,
     "At 3:00 the hands are 3 hour-marks apart, and 3 x 30 = 90 degrees."),
    (L, 2, "If CAT is coded as DBU (each letter shifted by +1), how is DOG coded?",
     ["EPH", "DPH", "EOH", "CPF"], 0,
     "D to E, O to P, G to H, so the code is EPH."),
    (L, 3, "Complete the analogy: 2 : 8 :: 3 : ?",
     ["9", "18", "24", "27"], 3,
     "2 is 2^3 = 8, so 3 maps to 3^3 = 27."),
    (L, 1, "If today is Monday, what day will it be three days from today?",
     ["Wednesday", "Thursday", "Friday", "Saturday"], 1,
     "Monday + 3 days = Thursday."),
    (L, 2, "Statements: All pens are books. All books are bags. Conclusion: All pens are bags. Is the conclusion valid?",
     ["Valid", "Invalid", "Cannot say", "Partially valid"], 0,
     "The relation is transitive: pens are within books, and books are within bags."),

    # ---- Verbal Ability ----
    (V, 1, "Choose the synonym of ABUNDANT.",
     ["Scarce", "Plentiful", "Rare", "Empty"], 1,
     "Abundant means plentiful."),
    (V, 1, "Choose the antonym of TRANSPARENT.",
     ["Clear", "Glass", "Opaque", "Bright"], 2,
     "Opaque means not allowing light through."),
    (V, 1, "Choose the correct verb: She ___ to the market every Sunday.",
     ["go", "goes", "going", "gone"], 1,
     "The simple present with a third-person singular subject takes -es."),
    (V, 1, "What does the idiom 'break the ice' mean?",
     ["To break something fragile", "To start a conversation or ease tension",
      "To feel very cold", "To give up a plan"], 1,
     "It means making people feel comfortable in a social setting."),
    (V, 1, "Choose the correctly spelled word.",
     ["Accommodation", "Acommodation", "Accomodation", "Acomodation"], 0,
     "It has a double 'c' and a double 'm'."),
    (V, 2, "Which single word means 'a person who knows everything'?",
     ["Omnipotent", "Omniscient", "Omnivore", "Omnipresent"], 1,
     "Omniscient means all-knowing."),
    (V, 2, "Find the error: 'Each of the students have submitted their forms.' Which part is incorrect?",
     ["Each of the students", "have submitted", "their forms", "No error"], 1,
     "'Each' is singular, so it should be 'has submitted'."),
    (V, 1, "Choose the correct article: He is ___ honest man.",
     ["a", "an", "the", "no article"], 1,
     "'Honest' starts with a silent h, so it takes 'an'."),

    # ---- Data Interpretation ----
    (D, 1, "Monthly sales were Jan 40, Feb 60, Mar 50 (units). What were the total sales for Jan to Mar?",
     ["130", "140", "150", "160"], 2,
     "40 + 60 + 50 = 150."),
    (D, 1, "What is the average of 12, 18, 24 and 30?",
     ["18", "20", "21", "24"], 2,
     "Sum = 84, and 84 / 4 = 21."),
    (D, 1, "Sales rose from 200 to 260. What is the percentage increase?",
     ["20%", "25%", "30%", "35%"], 2,
     "(60 / 200) x 100 = 30%."),
    (D, 2, "There are 1500 students and 40% of them are in Engineering. How many are in Engineering?",
     ["400", "500", "600", "700"], 2,
     "0.4 x 1500 = 600."),
    (D, 2, "Marks of five students are 60, 72, 58, 90 and 70. What is the median?",
     ["60", "65", "70", "72"], 2,
     "Sorted: 58, 60, 70, 72, 90. The middle value is 70."),
    (D, 3, "The ratio A:B is 2:3 and B:C is 3:4. What is A:C?",
     ["1:2", "2:3", "1:3", "3:4"], 0,
     "Make B equal to 3 in both ratios: A:B:C = 2:3:4, so A:C = 2:4 = 1:2."),
    (D, 2, "A price falls from 100 to 80. What is the percentage change?",
     ["-20%", "-25%", "-18%", "-30%"], 0,
     "(80 - 100) / 100 = -20%."),
    (D, 3, "A car travels at 60 km/h for 2 hours and then at 40 km/h for 1 hour. What is its average speed?",
     ["50 km/h", "52 km/h", "53.3 km/h", "55 km/h"], 2,
     "Total distance = 120 + 40 = 160 km over 3 hours, giving 53.3 km/h."),
]
